### ISSUE TITLE
Needs to specify Minimum Perl version of 5.14

### ISSUE THREAD

**Issue by tehmoth** [gshank/dbix-class-resultset-recursiveupdate#22]
uses non-destructive substitution (s//r) which was added in 5.14

**Comment by abraxxa** [comment]
Can you please link the affected line?
I can't find it.
Thanks!

**Comment by adherzog** [comment]
> Can you please link the affected line? I can't find it. Thanks!

https://github.com/gshank/dbix-class-resultset-recursiveupdate/blob/dfacccc200434353b2145672fdab813d141985f3/lib/DBIx/Class/ResultSet/RecursiveUpdate.pm#L65

**Comment by abraxxa** [comment]
Ah, thanks! This is why my /r search didn't bring it up ;-)
